// Generated by uniffi-bindgen-react-native
#include "react-native-phantom.h"
#include "generated/phantom_rs.hpp"

namespace phantom {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativePhantomRs::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}