[package]
name = "phantom-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
phantom-rs = { path = "../phantom-rs" }
clap = { version = "4.5.4", features = ["derive"] }
simplelog = "0.12.2"
log = "0.4.27"
tokio = "1.45.1"
tokio-util = "0.7.15"
