import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#18171c',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingTop: 24,
    marginBottom: 8,
  },
  logoContainer: {
    marginRight: 8,
  },
  logo: {
    fontSize: 40,
    color: '#b18fff',
  },
  headerTitle: {
    fontSize: 36,
    fontWeight: 'bold',
    color: '#fff',
    flex: 1,
  },
  addButton: {
    backgroundColor: '#f1a7ff',
    borderRadius: 24,
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addButtonText: {
    color: '#18171c',
    fontSize: 28,
    fontWeight: 'bold',
  },
  serversTitle: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#fff',
    marginLeft: 24,
    marginBottom: 16,
  },
  serversListContainer: {
    flex: 1,
    width: '100%',
    paddingHorizontal: 16,
  },
  noServersText: {
    color: '#b18fff',
    fontSize: 20,
    opacity: 0.7,
  },
  bottomNav: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 48,
    paddingVertical: 16,
    backgroundColor: '#18171c',
  },
  navIconActive: {
    width: 36,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#3b3bff',
  },
  navIcon: {
    width: 36,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#3b3bff',
    opacity: 0.3,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    width: '85%',
    backgroundColor: '#23222a',
    borderRadius: 24,
    padding: 24,
    alignItems: 'stretch',
  },
  modalTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#fff',
    alignSelf: 'center',
    marginBottom: 16,
  },
  modalLabel: {
    color: '#fff',
    fontWeight: 'bold',
    marginTop: 8,
    marginBottom: 4,
  },
  input: {
    backgroundColor: '#18171c',
    color: '#fff',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#3b3bff',
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: 18,
    marginBottom: 8,
  },
  modalButtonRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 16,
  },
  saveButton: {
    backgroundColor: '#2196F3',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 8,
    minWidth: 100,
    alignItems: 'center',
  },
  saveButtonDisabled: {
    backgroundColor: '#90CAF9',
    opacity: 0.7,
  },
  saveButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  cancelButton: {
    backgroundColor: '#E0E0E0',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 8,
    minWidth: 100,
    alignItems: 'center',
  },
  cancelButtonDisabled: {
    backgroundColor: '#F5F5F5',
    opacity: 0.7,
  },
  cancelButtonText: {
    color: '#424242',
    fontSize: 16,
    fontWeight: '600',
  },
  // Server List Styles
  serverList: {
    flex: 1,
    width: '100%',
  },
  serverItem: {
    backgroundColor: '#2A2A2A',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    width: '100%',
    alignSelf: 'stretch',
  },
  serverHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    width: '100%',
  },
  serverInfo: {
    flex: 1,
    marginLeft: 12,
    marginRight: 8,
  },
  serverName: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 4,
  },
  serverAddress: {
    color: '#AAAAAA',
    fontSize: 14,
  },
  serverDetails: {
    marginTop: 8,
  },
  serverStats: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  lastUpdated: {
    fontSize: 12,
    color: '#666',
  },
  lastUpdatedPlaceholder: {
    height: 12,
    width: 80,
    backgroundColor: '#eee',
    borderRadius: 4,
  },
  lastUpdatedSkeleton: {
    height: '100%',
    width: '100%',
    backgroundColor: '#3a3a3a',
    borderRadius: 4,
  },
  statusIndicator: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginLeft: 8,
  },
  moreOptionsButton: {
    marginLeft: 8,
    padding: 8,
    borderRadius: 16,
  },
  moreOptionsText: {
    color: '#FFFFFF',
    fontSize: 24,
    fontWeight: 'bold',
    lineHeight: 24,
  },
  deleteButton: {
    backgroundColor: '#F44336',
    borderRadius: 12,
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 8,
  },
  deleteButtonText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: 'bold',
    lineHeight: 22,
  },
  serverIcon: {
    width: 40,
    height: 40,
    borderRadius: 8,
    backgroundColor: '#3A3A3A',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  serverIconPlaceholder: {
    width: 40,
    height: 40,
    borderRadius: 8,
    backgroundColor: '#2A2A2A',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  serverIconInner: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 4,
  },
  serverIconLine: {
    height: 2,
    width: '40%',
    backgroundColor: '#666666',
    borderRadius: 1,
  },
  serverIconPlaceholderText: {
    color: '#666666',
    fontSize: 20,
    fontWeight: 'bold',
  },
  playerCount: {
    color: '#AAAAAA',
    fontSize: 14,
    marginBottom: 8,
  },
  playerCountPlaceholder: {
    height: 20,
    marginBottom: 8,
  },
  playerCountSkeleton: {
    height: 14,
    width: 100,
    backgroundColor: '#3A3A3A',
    borderRadius: 4,
  },
  motdContainer: {
    marginTop: 4,
  },
  motdLine: {
    color: '#CCCCCC',
    fontSize: 14,
    marginBottom: 2,
  },
  motdPlaceholder: {
    marginTop: 4,
  },
  motdSkeleton: {
    height: 14,
    width: '90%',
    backgroundColor: '#3A3A3A',
    borderRadius: 4,
    marginBottom: 4,
  },
  emptyState: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 32,
  },
  emptyStateText: {
    color: '#AAAAAA',
    fontSize: 16,
  },
  // Form Validation Styles
  inputError: {
    borderColor: '#F44336',
  },
  errorText: {
    color: '#F44336',
    fontSize: 12,
    marginTop: 4,
    marginBottom: 8,
  },
  // Loading and Error States
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    color: '#AAAAAA',
    fontSize: 16,
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  menuContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    minWidth: 160,
    zIndex: 1000,
    position: 'absolute',
  },
  menuRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginTop: 8,
  },
  menuButton: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
    backgroundColor: '#3A3A3A',
    minWidth: 80,
    alignItems: 'center',
  },
  menuButtonDestructive: {
    backgroundColor: '#FF3B30',
  },
  menuButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  menuButtonTextDestructive: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
});
