// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "react-native-phantom.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "PhantomSpec.h"

@interface Phantom : NSObject <NativePhantomSpec>
#else
#import <React/RCTBridgeModule.h>

@interface Phantom : NSObject <RCTBridgeModule>
#endif

@end